services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:      
      - 5432:5432
    volumes:
      - ./postgres-data-askguru:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant-data-askguru:/qdrant/storage
volumes:
  postgres-data-askguru:
  qdrant-data-askguru: