import type { Metadata } from "next";
import { Noticia_Text, Fira_Sans_Extra_Condensed, Numans} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import AuthProvider from "@/components/providers/authProvider";


const noticia = Noticia_Text({
  variable: "--font-noticia",
  weight: '400',
  subsets: ["latin"]
})

const firaSans = Fira_Sans_Extra_Condensed({
  variable: "--font-firaSans",
  weight: '100',
  subsets: ["cyrillic"]
})

const numans = Numans({
  variable: '--font-numans',
  weight: '400',
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${firaSans.variable} ${noticia.variable} ${numans.variable} antialiased tracking-wider`}
      >
        <AuthProvider>
             <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          </AuthProvider>
      </body>
    </html>
  );
}
